apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ggi3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-service-tenant/appstudio/dc-metro-map-ggi3@sha256:99126760d51d64f8260522629366fff737059f39643cca62647fca75828f1f12
        name: my-nodejs
        resources: {}
status: {}
